Todo/urls.py
from django.contrib.auth import views
from django.urls import path
from .views import *

urlpatterns = [
    path('', user_tasks, name='user_tasks'),
    path('registration/', user_registration, name='registration'),
    path('authentication/', user_login, name='authentication'),
    path('task_creation/', user_task_creation, name='task_creation'),
    path('logout/', user_logout, name='logout'),
    path('category/<slug:cat_slug>/task/<int:task_id>/', task_detail, name='detail'),
    path('category/<slug:cat_slug>/task/<int:task_id>/update/', task_update, name='update'),
    path('task_delete/task/<int:task_id>/', task_delete, name='delete'),
    path('tasks/<slug:cat_slug>/<int:cat_id>/', tasks_by_category, name='by_category'),
    path('account_settings/', user_profile, name='account'),
    path('user_change_password/', user_change_password, name='change_password'),
    path('reset_password/', reset_password_page, name='reset_password_page'),
    path('user_reset_password/', user_reset_password, name='reset_password'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(template_name='Todo/confirmation.html'),
         name='confirmation'),
    path('reset/done/', views.PasswordResetDoneView.as_view(template_name='Todo/reset_done.html'),
         name='password_reset_complete'),
    path('mail_change/', user_change_email, name='change_email'),
    path('mail_change_process/', change_email_process, name='change_email_process')
]

TodoList/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('my_todolist/', include('Todo.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Todo/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=250, verbose_name='Name of tasks category')
    slug = models.SlugField(unique=True, verbose_name='Category slug', blank=True)

    def __str__(self):
        return f'Category: {self.name}'

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Todo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, verbose_name='User')
    title = models.CharField(max_length=450, verbose_name='Title of task')
    description = models.TextField(blank=True, verbose_name='Description of task')
    complete = models.BooleanField(default=False, verbose_name='The task completed or not?')
    created = models.DateTimeField(auto_now_add=True)
    date = models.DateField(default=timezone.now().strftime('%Y-%m-%d'), verbose_name='Date of task creation',
                            blank=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, null=True, verbose_name='Category')

    def __str__(self):
        return f'User: {self.user.username}, task: {self.title}'

    class Meta:
        verbose_name = 'Todo'
        verbose_name_plural = 'Todos'
        ordering = ['-created']

Todo/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm, PasswordResetForm, \
    SetPasswordForm
from django.contrib.auth.models import User
from django.contrib import messages

from .models import Todo, Category


class Registration(UserCreationForm):
    username = forms.CharField(label='Write here the username that you want',
                               widget=forms.TextInput(attrs={'class': 'form-control',
                                                             'placeholder': 'Username'}))
    password1 = forms.CharField(label='Create you password',
                                widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))
    password2 = forms.CharField(label='Repeat your password here', widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Repeat your password'}))
    email = forms.EmailField(label='Write here your email',
                             widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class Authentication(AuthenticationForm):
    username = forms.CharField(label='Write here your username',
                               widget=forms.TextInput(attrs={'class': 'form-control',
                                                             'placeholder': 'Username'}))
    password = forms.CharField(label='Write here your password',
                               widget=forms.TextInput(
                                   attrs={'class': 'form-control', 'placeholder': 'password', 'type': 'password'}))


class TaskCreation(forms.ModelForm):
    class Meta:
        model = Todo
        fields = ['title', 'description', 'category']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 5}),
            'category': forms.Select(attrs={'class': 'form-control'}),
        }


class TaskUpdate(forms.ModelForm):
    title = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    complete = forms.BooleanField(required=False)
    description = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 5}))
    category = forms.ModelChoiceField(queryset=Category.objects.all(), required=False,
                                      widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = Todo
        fields = ['title', 'complete', 'description', 'category']


class UserPasswordChange(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class UserResetPassword(PasswordResetForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))


class UserChangeEmail(forms.Form):
    code = forms.CharField(label='Code',
                           help_text='Write here four-digit code which was sent to your email',
                           widget=forms.TextInput({'class': 'form-control'}))
    new_email = forms.EmailField(label='Your new email',
                                 widget=forms.EmailInput(attrs={'class': 'form-control'}))

Todo/views.py
import random
from django.contrib.auth import login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from .forms import Registration, Authentication, TaskCreation, TaskUpdate, UserPasswordChange, UserResetPassword, \
    UserChangeEmail
from .tasks import *
from .models import Todo, Category


def user_registration(request):
    if request.user.is_authenticated:
        return redirect('user_tasks')
    else:
        if request.method == 'POST':
            form = Registration(request.POST)
            if form.is_valid():
                users_emails = []
                for item in User.objects.all():
                    users_emails.append(item.email)
                if form.cleaned_data['email'] in users_emails:
                    messages.error(request, 'User with this email is already exists')
                    return redirect(request.path)
                else:
                    user = form.save()
                    login(request, user)
                    messages.success(request, 'You successfully created account')
                    send_registration_mail.delay(user.username, user.email)
                    return redirect('user_tasks')
        else:
            form = Registration()
        return render(request, 'Todo/registration_page.html', {'form': form})


def user_login(request):
    reset_form = UserResetPassword()
    if request.user.is_authenticated:
        return redirect('user_tasks')
    else:
        if request.method == 'POST':
            form = Authentication(data=request.POST)
            if form.is_valid():
                user = form.get_user()
                login(request, user)
                messages.success(request, 'You successfully authenticated!')
                return redirect('user_tasks')
        else:
            form = Authentication()
        return render(request, 'Todo/authentication_page.html', {'form': form, 'reset_form': reset_form})


def user_task_creation(request):
    if request.method == 'POST':
        form = TaskCreation(request.POST)
        if form.is_valid():
            task = Todo()
            task.user = request.user
            task.title = form.cleaned_data['title']
            task.description = form.cleaned_data['description']
            task.category = form.cleaned_data['category']
            task.save()

            task_creation_mail.delay(request.user.username, request.user.email, task.title, task.description,
                                     task.category.name)

            messages.success(request, f'Task created successfully')
            return redirect('user_tasks')

    else:
        form = TaskCreation()
    return render(request, 'Todo/task_creation.html', {'form': form})


@login_required(login_url='/my_todolist/registration')
def user_tasks(request):
    tasks = Todo.objects.filter(user=request.user).select_related('category')

    return render(request, 'Todo/user_tasks.html', {'tasks': tasks})


@login_required(login_url='/my_todolist/registration')
def user_logout(request):
    logout(request)
    return redirect('authentication')


@login_required(login_url='/my_todolist/registration')
def task_detail(request, task_id, cat_slug):
    task = get_object_or_404(Todo, user=request.user, id=task_id)

    cat_slug = Category.objects.get(slug=cat_slug)

    return render(request, 'Todo/task_detail.html', {'task': task})


@login_required(login_url='/my_todolist/registration')
def task_update(request, task_id, cat_slug):
    task = Todo.objects.get(id=task_id, user=request.user)

    task_title = task.title
    task_desc = task.description
    task_cat = task.category
    task_date = task.date

    cat_slug = Category.objects.get(slug=cat_slug)

    if request.method == 'POST':
        form = TaskUpdate(request.POST)
        if form.is_valid():
            task.title = form.cleaned_data['title'] or task_title
            task.complete = form.cleaned_data['complete']
            task.description = form.cleaned_data['description'] or task_desc
            task.category = form.cleaned_data['category'] or task_cat
            task.date = form.cleaned_data['date'] or task_date
            task.save()

            task_updating_mail.delay(request.user.username, request.user.email, task.title)

            messages.success(request, 'Task was updated successfully')
            return redirect('user_tasks')
    else:
        form = TaskUpdate()
    return render(request, 'Todo/task_update.html', {'form': form, 'task': task})


@login_required(login_url='/my_todolist/registration')
def task_delete(request, task_id):
    task = Todo.objects.get(id=task_id, user=request.user)
    task.delete()

    return redirect('user_tasks')


@login_required(login_url='/my_todolist/registration')
def tasks_by_category(request, cat_id, cat_slug):
    category = Category.objects.get(id=cat_id, slug=cat_slug)
    tasks = Todo.objects.filter(user=request.user, category_id=cat_id).select_related('category')

    context = {
        'category': category,
        'tasks': tasks
    }
    return render(request, template_name='Todo/tasks_by_category.html', context=context)


@login_required(login_url='/my_todolist/authentication')
def user_profile(request):
    form = UserPasswordChange(user=request.user)

    reset_form = UserResetPassword()
    change_email_form = UserChangeEmail()
    context = {
        'form': form,
        'reset_form': reset_form,
        'change_email_form': change_email_form
    }

    return render(request, template_name='Todo/user_page.html', context=context)


@login_required(login_url='/my_todolist/authentication')
def user_change_password(request):
    if request.method == 'POST':
        form = UserPasswordChange(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'You successfully changed your password!')
    return redirect('authentication')


def reset_password_page(request):
    reset_form = UserResetPassword()
    return render(request, 'Todo/reset_form_page.html', {'reset_form': reset_form})


def user_reset_password(request):
    if request.method == 'POST':
        reset_form = UserResetPassword(request.POST)
        if reset_form.is_valid():
            mail = reset_form.cleaned_data['email']

            user = User.objects.get(email=mail)

            if user:
                subject = 'Requested password reset'
                email_template_name = 'Todo/reset_password_mail.html'
                cont = {
                    'email': mail,
                    'domain': '127.0.0.1:8000',
                    'site_name': 'TodoList',
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'user': user,
                    'token': default_token_generator.make_token(user),
                    'protocol': 'http',
                }
                msg_html = render_to_string(email_template_name, cont)
                send_mail(subject, 'ссылка', 'kuzmenkowebdev@gmail.com', [mail], fail_silently=False,
                          html_message=msg_html)
                messages.success(request, 'Mail was sent successfully!')
    return redirect('authentication')


def user_change_email(request):
    code = random.randint(1000, 9999)
    request.session['change_code'] = str(code)

    subject = 'You send request for changing your email address at the TodoList site'
    message = f'Your code: {code}'
    send_mail(subject, message, 'kuzmenkowebdev@gmail.com', [request.user.email], fail_silently=False)
    messages.success(request, 'Mail with the code was sent successfully!')

    return redirect('account')


def change_email_process(request):
    if request.method == 'POST':
        change_email_form = UserChangeEmail(request.POST)
        if change_email_form.is_valid():
            code = change_email_form.cleaned_data['code']
            if code == request.session['change_code']:
                del request.session['change_code']
                request.user.email = change_email_form.cleaned_data['new_email']
                request.user.save()
                messages.success(request, 'You successfully changed your email!')
            else:
                messages.error(request, 'The code is wrong, write it again')
    return redirect('account')

Todo/templates/Todo/authentication_page.html
{% extends 'base.html' %}

{% block title %}
    Authentication
{% endblock %}

{% block sidebar %}
    {% include 'inc/_sidebar.html' %}
{% endblock %}

{% block content %}
    <h1>Authentication</h1>

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <div class="d-flex justify-content-between">
            <button type="submit" class="btn btn-success btn-block">Authenticate</button>
            <a href="{% url 'reset_password_page' %}" style="margin-left: 300px; margin-top: 10px"><h5>Forgot your
                password?</h5></a>
        </div>

    </form>

{% endblock %}

Todo/templates/Todo/confirmation.html
{% extends 'base.html' %}

{% block title %}
    Password reset done
{% endblock %}

{% block content %}

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}

{#        <div class="form-group">#}
{#            <label for="id_new_password1">New password:</label>#}
{#            <input type="password" name="new_password1" autocomplete="new-password" required id="id_new_password1"#}
{#                   class="form-control">#}
{#            <p>{{ form.new_password1.erorrs|striptags }}</p>#}
{#        </div>#}
{##}
{#        <div class="form-group">#}
{#            <label for="id_new_password2">New password confirm:</label>#}
{#            <input type="password" name="new_password2" autocomplete="new-password" required id="id_new_password2"#}
{#                   class="form-control">#}
{#            <p>{{ form.new_password2.erorrs|striptags }}</p>#}
{#        </div>#}

        <button type="submit" class="btn btn-danger">RESET PASSWORD</button>
    </form>
{% endblock %}

Todo/templates/Todo/registration_page.html
{% extends 'base.html' %}

{% block title %}
    Registration
{% endblock %}

{% block sidebar %}
    {% include 'inc/_sidebar.html' %}
{% endblock %}

{% block content %}
    <h1>Registration</h1>

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="btn btn-success btn-block">Register</button>

    </form>

{% endblock %}

Todo/templates/Todo/reset_done.html
{% extends 'base.html' %}

{% block title %}

{% endblock %}

{% block content %}
    <h1 class="reset-success" style="color: green">You successfully reset your password!</h1>
{% endblock %}

Todo/templates/Todo/reset_form_page.html
{% extends 'base.html' %}

{% block title %}
    Reset password
{% endblock %}

{% block sidebar %}
    {% include 'inc/_sidebar.html' %}
{% endblock %}

{% block content %}
    <h4 class="reset_password" style="margin-top: 50px">Reset password:</h4>
    <form action="{% url 'reset_password' %}" method="post">

        {% csrf_token %}
        {{ reset_form.as_p }}
        <button type="submit" class="btn btn-success">Send mail</button>

    </form>
{% endblock %}

Todo/templates/Todo/reset_password_mail.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>


<h1>Reset your password</h1>

<a href="{{ protocol }}://{{ domain }}{% url 'confirmation' uidb64=uid token=token %}" class="btn btn-success">
    RESET PASSWORD
</a>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
        integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD"
        crossorigin="anonymous"></script>
</body>
</html>

Todo/templates/Todo/task_creation.html
{% extends 'base.html' %}

{% block title %}
    Tasks creation
{% endblock %}

{% block sidebar %}
    {% include 'inc/_sidebar.html' %}
{% endblock %}

{% block content %}
    <h1>Create task</h1>
    <a href="{% url 'user_tasks' %}"><h5>Go to all tasks page</h5></a>
    <br>
    <br>

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="btn btn-success btn-block">Create</button>

    </form>

{% endblock %}

Todo/templates/Todo/task_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ task.title }}
{% endblock %}

{% block sidebar %}
    {% include 'inc/_sidebar.html' %}
{% endblock %}


{% block content %}



    <h1>Task: {{ task.title }}</h1>
    <a href="{% url 'user_tasks' %}"><h5>Go to all tasks</h5></a>
    <br>
    <br>

    <div class="card" style="margin-top: 40px">
        <div class="card-body">
            <h2 class="card-title">{{ task.title }}</h2>
            <p class="card-text"><h5>{{ task.description }}</h5></p>
            {% if task.complete %}
                <p class="card-text">Task status: completed</p>
            {% else %}
                <p class="card-text">Task status: not completed</p>
            {% endif %}

            {% if task.complete %}
                <a href="{% url 'delete' task.id %}" class="btn btn-danger">Delete</a>
            {% else %}
                <a href="{% url 'update' task.category.slug task.id %}" class="btn btn-success">Update</a>
                <a href="{% url 'delete' task.id %}" class="btn btn-danger">Delete</a>
            {% endif %}

        </div>
    </div>

{% endblock %}

Todo/templates/Todo/task_update.html
{% extends 'base.html' %}

{% block title %}
    Task update
{% endblock %}

{% block sidebar %}
    {% include 'inc/_sidebar.html' %}
{% endblock %}

{% block content %}



    <h1>Update task</h1>
    <h3>Change only the fields you want to update</h3>
    <a href="{% url 'detail' task.category.slug task.id %}"><h5>Go to detail page of this task</h5></a>
    <br>
    <br>



    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="btn btn-success btn-block">Update</button>

    </form>

{% endblock %}

Todo/templates/Todo/tasks_by_category.html
{% extends 'base.html' %}

{% block title %}
    {{ category.name }}
{% endblock %}

{% block sidebar %}
    {% include 'inc/_sidebar.html' %}
{% endblock %}

{% block content %}

    {% if 'tasks' in category.name %}
        <h1>{{ category.name }}</h1>
    {% else %}
        <h1>{{ category.name }}</h1>
    {% endif %}

    {% if tasks|length > 0 %}
        <a href="{% url 'task_creation' %}"><h5>Create new task</h5></a>
    {% endif %}


    {% if tasks|length > 0 %}

        {% for task in tasks %}
            <div class="card" style="border-width: 1px; border-color: black !important; margin-top: 40px">
                <div class="card-body">
                    <h2 class="card-title">{{ task.title }}</h2>
                    <p class="card-text"><h5>{{ task.description|truncatewords:7 }}</h5></p>
                    {% if task.complete %}
                        <p class="card-text">Task status: completed</p>
                    {% else %}
                        <p class="card-text">Task status: not completed</p>
                    {% endif %}
                    <a href="{% url 'detail' task.category.slug task.id %}" class="btn btn-primary">Check details</a>
                    {% if task.complete %}
                        <a href="{% url 'delete' task.id %}" class="btn btn-danger">Delete</a>
                    {% else %}
                        <a href="{% url 'update' task.category.slug task.id %}" class="btn btn-success">Update</a>
                        <a href="{% url 'delete' task.id %}" class="btn btn-danger">Delete</a>
                    {% endif %}
                </div>
            </div>
        {% endfor %}

    {% else %}
        <h3>Now u don't have tasks in this category, click the button to create it</h3>
        <a href="{% url 'task_creation' %}" class="button btn btn-success">Create my first task</a>
    {% endif %}




{% endblock %}

Todo/templates/Todo/user_page.html
{% extends 'base.html' %}

{% block title %}
    {{ request.user.username }} - personal area
{% endblock %}

{% block content %}

    <h1>Account settings</h1>

    <h4 class="password_change" style="margin-top: 50px">Change my password:</h4>
    <form action="{% url 'change_password' %}" method="post">

        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Change</button>

    </form>

    <h4 class="email_change" style="margin-top: 50px">Change my email</h4>
    <a href="{% url 'change_email' %}" class="btn btn-success">Send code to the email</a>

    <form action="{% url 'change_email_process' %}" method="post" style="margin-top: 20px; margin-bottom: 60px">
        {% csrf_token %}
        {{ change_email_form.as_p }}

        <button type="submit" class="btn btn-success">Change</button>
    </form>

{% endblock %}

Todo/templates/Todo/user_tasks.html
{% extends 'base.html' %}

{% block title %}
    My tasks
{% endblock %}

{% block sidebar %}
    {% include 'inc/_sidebar.html' %}
{% endblock %}

{% block content %}

    <h1>My all tasks</h1>
    {% if tasks|length > 0 %}
        <a href="{% url 'task_creation' %}"><h5>Create new task</h5></a>
    {% endif %}


    {% if tasks|length > 0 %}

        {% for task in tasks %}
            <div class="card"
                 style="border-width: 1px; border-color: black !important; margin-top: 40px; margin-bottom: 50px">
                <div class="card-header">
                    Category: {{ task.category.name }}
                </div>
                <div class="card-body">
                    <h2 class="card-title">{{ task.title }}</h2>
                    <p class="card-text"><h5>{{ task.description|truncatewords:7 }}</h5></p>
                    {% if task.complete %}
                        <p class="card-text">Task status: completed</p>
                    {% else %}
                        <p class="card-text">Task status: not completed</p>
                    {% endif %}
                    <p class="card-text">Deadline: {{ task.date }}</p>
                    <a href="{% url 'detail' task.category.slug task.id %}" class="btn btn-primary">Check details</a>
                    {% if task.complete %}
                        <a href="{% url 'delete' task.id %}" class="btn btn-danger">Delete</a>
                    {% else %}
                        <a href="{% url 'update' task.category.slug task.id %}" class="btn btn-success">Update</a>
                        <a href="{% url 'delete' task.id %}" class="btn btn-danger">Delete</a>
                    {% endif %}
                </div>
            </div>
        {% endfor %}

    {% else %}
        <h3>Now u don't have tasks, click the button to create it</h3>
        <a href="{% url 'task_creation' %}" class="button btn btn-success">Create my first task</a>
    {% endif %}




{% endblock %}